version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: 
          name: Run tests
          command: |
            . venv/bin/activate
            pytest zip_archive
